from qiskit import QuantumRegister, ClassicalRegister, QuantumCircuit

qreg_q = QuantumRegister(5, 'q')
creg_c = ClassicalRegister(5, 'c')
circuit = QuantumCircuit(qreg_q, creg_c)

# --- INICIO DEL MURO DE SEÑUELOS ---

# Capa de señuelo 1
circuit.delay(1006, qreg_q[0], unit='dt')
circuit.s(qreg_q[0])
circuit.delay(1456, qreg_q[1], unit='dt')
circuit.x(qreg_q[1])
circuit.delay(1126, qreg_q[2], unit='dt')
circuit.s(qreg_q[2])
circuit.delay(2302, qreg_q[3], unit='dt')
circuit.y(qreg_q[3])
circuit.delay(169, qreg_q[4], unit='dt')
circuit.z(qreg_q[4])
circuit.barrier()

# Capa de señuelo 2
circuit.delay(369, qreg_q[0], unit='dt')
circuit.z(qreg_q[0])
circuit.delay(1010, qreg_q[1], unit='dt')
circuit.z(qreg_q[1])
circuit.delay(238, qreg_q[2], unit='dt')
circuit.s(qreg_q[2])
circuit.delay(2574, qreg_q[3], unit='dt')
circuit.x(qreg_q[3])
circuit.delay(2007, qreg_q[4], unit='dt')
circuit.h(qreg_q[4])
circuit.barrier()

# Capa de señuelo 3
circuit.delay(1568, qreg_q[0], unit='dt')
circuit.z(qreg_q[0])
circuit.delay(1258, qreg_q[1], unit='dt')
circuit.h(qreg_q[1])
circuit.delay(607, qreg_q[2], unit='dt')
circuit.s(qreg_q[2])
circuit.delay(386, qreg_q[3], unit='dt')
circuit.z(qreg_q[3])
circuit.delay(608, qreg_q[4], unit='dt')
circuit.h(qreg_q[4])
circuit.barrier()

# Capa de señuelo 4
circuit.delay(1518, qreg_q[0], unit='dt')
circuit.x(qreg_q[0])
circuit.delay(1100, qreg_q[1], unit='dt')
circuit.h(qreg_q[1])
circuit.delay(147, qreg_q[2], unit='dt')
circuit.s(qreg_q[2])
circuit.delay(1565, qreg_q[3], unit='dt')
circuit.z(qreg_q[3])
circuit.delay(2672, qreg_q[4], unit='dt')
circuit.h(qreg_q[4])
circuit.barrier()

# Capa de señuelo 5
circuit.delay(839, qreg_q[0], unit='dt')
circuit.h(qreg_q[0])
circuit.delay(2766, qreg_q[1], unit='dt')
circuit.s(qreg_q[1])
circuit.delay(712, qreg_q[2], unit='dt')
circuit.s(qreg_q[2])
circuit.delay(930, qreg_q[3], unit='dt')
circuit.z(qreg_q[3])
circuit.delay(1823, qreg_q[4], unit='dt')
circuit.x(qreg_q[4])
circuit.barrier()

# Capa de señuelo 6
circuit.delay(2613, qreg_q[0], unit='dt')
circuit.s(qreg_q[0])
circuit.delay(1271, qreg_q[1], unit='dt')
circuit.s(qreg_q[1])
circuit.delay(1670, qreg_q[2], unit='dt')
circuit.s(qreg_q[2])
circuit.delay(2448, qreg_q[3], unit='dt')
circuit.y(qreg_q[3])
circuit.delay(1377, qreg_q[4], unit='dt')
circuit.x(qreg_q[4])
circuit.barrier()

# Capa de señuelo 7
circuit.delay(2150, qreg_q[0], unit='dt')
circuit.x(qreg_q[0])
circuit.delay(1821, qreg_q[1], unit='dt')
circuit.h(qreg_q[1])
circuit.delay(2980, qreg_q[2], unit='dt')
circuit.z(qreg_q[2])
circuit.delay(2584, qreg_q[3], unit='dt')
circuit.h(qreg_q[3])
circuit.delay(709, qreg_q[4], unit='dt')
circuit.h(qreg_q[4])
circuit.barrier()

# Capa de señuelo 8
circuit.delay(2983, qreg_q[0], unit='dt')
circuit.x(qreg_q[0])
circuit.delay(950, qreg_q[1], unit='dt')
circuit.z(qreg_q[1])
circuit.delay(1221, qreg_q[2], unit='dt')
circuit.y(qreg_q[2])
circuit.delay(1990, qreg_q[3], unit='dt')
circuit.y(qreg_q[3])
circuit.delay(1948, qreg_q[4], unit='dt')
circuit.s(qreg_q[4])
circuit.barrier()

# Capa de señuelo 9
circuit.delay(1810, qreg_q[0], unit='dt')
circuit.s(qreg_q[0])
circuit.delay(685, qreg_q[1], unit='dt')
circuit.z(qreg_q[1])
circuit.delay(2198, qreg_q[2], unit='dt')
circuit.s(qreg_q[2])
circuit.delay(1206, qreg_q[3], unit='dt')
circuit.s(qreg_q[3])
circuit.delay(1096, qreg_q[4], unit='dt')
circuit.y(qreg_q[4])
circuit.barrier()

# Capa de señuelo 10
circuit.delay(866, qreg_q[0], unit='dt')
circuit.s(qreg_q[0])
circuit.delay(342, qreg_q[1], unit='dt')
circuit.z(qreg_q[1])
circuit.delay(1982, qreg_q[2], unit='dt')
circuit.h(qreg_q[2])
circuit.delay(2126, qreg_q[3], unit='dt')
circuit.z(qreg_q[3])
circuit.delay(659, qreg_q[4], unit='dt')
circuit.h(qreg_q[4])
circuit.barrier()

# Capa de señuelo 11
circuit.delay(1074, qreg_q[0], unit='dt')
circuit.y(qreg_q[0])
circuit.delay(1041, qreg_q[1], unit='dt')
circuit.s(qreg_q[1])
circuit.delay(1585, qreg_q[2], unit='dt')
circuit.h(qreg_q[2])
circuit.delay(630, qreg_q[3], unit='dt')
circuit.z(qreg_q[3])
circuit.delay(1263, qreg_q[4], unit='dt')
circuit.x(qreg_q[4])
circuit.barrier()

# Capa de señuelo 12
circuit.delay(1429, qreg_q[0], unit='dt')
circuit.x(qreg_q[0])
circuit.delay(143, qreg_q[1], unit='dt')
circuit.x(qreg_q[1])
circuit.delay(338, qreg_q[2], unit='dt')
circuit.h(qreg_q[2])
circuit.delay(1229, qreg_q[3], unit='dt')
circuit.y(qreg_q[3])
circuit.delay(2838, qreg_q[4], unit='dt')
circuit.h(qreg_q[4])
circuit.barrier()

# Capa de señuelo 13
circuit.delay(2245, qreg_q[0], unit='dt')
circuit.h(qreg_q[0])
circuit.delay(1191, qreg_q[1], unit='dt')
circuit.h(qreg_q[1])
circuit.delay(436, qreg_q[2], unit='dt')
circuit.x(qreg_q[2])
circuit.delay(1077, qreg_q[3], unit='dt')
circuit.h(qreg_q[3])
circuit.delay(525, qreg_q[4], unit='dt')
circuit.x(qreg_q[4])
circuit.barrier()

# Capa de señuelo 14
circuit.delay(2889, qreg_q[0], unit='dt')
circuit.x(qreg_q[0])
circuit.delay(1211, qreg_q[1], unit='dt')
circuit.z(qreg_q[1])
circuit.delay(1491, qreg_q[2], unit='dt')
circuit.h(qreg_q[2])
circuit.delay(107, qreg_q[3], unit='dt')
circuit.h(qreg_q[3])
circuit.delay(1200, qreg_q[4], unit='dt')
circuit.z(qreg_q[4])
circuit.barrier()

# Capa de señuelo 15
circuit.delay(339, qreg_q[0], unit='dt')
circuit.x(qreg_q[0])
circuit.delay(780, qreg_q[1], unit='dt')
circuit.y(qreg_q[1])
circuit.delay(588, qreg_q[2], unit='dt')
circuit.x(qreg_q[2])
circuit.delay(1873, qreg_q[3], unit='dt')
circuit.y(qreg_q[3])
circuit.delay(2954, qreg_q[4], unit='dt')
circuit.h(qreg_q[4])
circuit.barrier()

# Capa de señuelo 16
circuit.delay(1446, qreg_q[0], unit='dt')
circuit.s(qreg_q[0])
circuit.delay(2668, qreg_q[1], unit='dt')
circuit.h(qreg_q[1])
circuit.delay(1504, qreg_q[2], unit='dt')
circuit.x(qreg_q[2])
circuit.delay(2046, qreg_q[3], unit='dt')
circuit.s(qreg_q[3])
circuit.delay(2914, qreg_q[4], unit='dt')
circuit.y(qreg_q[4])
circuit.barrier()

# Capa de señuelo 17
circuit.delay(2894, qreg_q[0], unit='dt')
circuit.h(qreg_q[0])
circuit.delay(827, qreg_q[1], unit='dt')
circuit.z(qreg_q[1])
circuit.delay(2296, qreg_q[2], unit='dt')
circuit.s(qreg_q[2])
circuit.delay(2590, qreg_q[3], unit='dt')
circuit.h(qreg_q[3])
circuit.delay(230, qreg_q[4], unit='dt')
circuit.y(qreg_q[4])
circuit.barrier()

# Capa de señuelo 18
circuit.delay(1256, qreg_q[0], unit='dt')
circuit.y(qreg_q[0])
circuit.delay(2718, qreg_q[1], unit='dt')
circuit.x(qreg_q[1])
circuit.delay(2030, qreg_q[2], unit='dt')
circuit.x(qreg_q[2])
circuit.delay(2279, qreg_q[3], unit='dt')
circuit.s(qreg_q[3])
circuit.delay(2858, qreg_q[4], unit='dt')
circuit.x(qreg_q[4])
circuit.barrier()

# Capa de señuelo 19
circuit.delay(1870, qreg_q[0], unit='dt')
circuit.x(qreg_q[0])
circuit.delay(2576, qreg_q[1], unit='dt')
circuit.h(qreg_q[1])
circuit.delay(1286, qreg_q[2], unit='dt')
circuit.s(qreg_q[2])
circuit.delay(160, qreg_q[3], unit='dt')
circuit.s(qreg_q[3])
circuit.delay(2694, qreg_q[4], unit='dt')
circuit.h(qreg_q[4])
circuit.barrier()

# Capa de señuelo 20
circuit.delay(2021, qreg_q[0], unit='dt')
circuit.y(qreg_q[0])
circuit.delay(1126, qreg_q[1], unit='dt')
circuit.s(qreg_q[1])
circuit.delay(2888, qreg_q[2], unit='dt')
circuit.z(qreg_q[2])
circuit.delay(2053, qreg_q[3], unit='dt')
circuit.x(qreg_q[3])
circuit.delay(631, qreg_q[4], unit='dt')
circuit.z(qreg_q[4])
circuit.barrier()

# Capa de señuelo 21
circuit.delay(2661, qreg_q[0], unit='dt')
circuit.s(qreg_q[0])
circuit.delay(274, qreg_q[1], unit='dt')
circuit.y(qreg_q[1])
circuit.delay(1042, qreg_q[2], unit='dt')
circuit.s(qreg_q[2])
circuit.delay(704, qreg_q[3], unit='dt')
circuit.h(qreg_q[3])
circuit.delay(489, qreg_q[4], unit='dt')
circuit.s(qreg_q[4])
circuit.barrier()

# Capa de señuelo 22
circuit.delay(2759, qreg_q[0], unit='dt')
circuit.s(qreg_q[0])
circuit.delay(1760, qreg_q[1], unit='dt')
circuit.y(qreg_q[1])
circuit.delay(1751, qreg_q[2], unit='dt')
circuit.y(qreg_q[2])
circuit.delay(2346, qreg_q[3], unit='dt')
circuit.h(qreg_q[3])
circuit.delay(2117, qreg_q[4], unit='dt')
circuit.x(qreg_q[4])
circuit.barrier()

# Capa de señuelo 23
circuit.delay(683, qreg_q[0], unit='dt')
circuit.x(qreg_q[0])
circuit.delay(2029, qreg_q[1], unit='dt')
circuit.x(qreg_q[1])
circuit.delay(2151, qreg_q[2], unit='dt')
circuit.y(qreg_q[2])
circuit.delay(2739, qreg_q[3], unit='dt')
circuit.y(qreg_q[3])
circuit.delay(2252, qreg_q[4], unit='dt')
circuit.y(qreg_q[4])
circuit.barrier()

# Capa de señuelo 24
circuit.delay(1689, qreg_q[0], unit='dt')
circuit.y(qreg_q[0])
circuit.delay(1170, qreg_q[1], unit='dt')
circuit.z(qreg_q[1])
circuit.delay(2040, qreg_q[2], unit='dt')
circuit.z(qreg_q[2])
circuit.delay(1090, qreg_q[3], unit='dt')
circuit.x(qreg_q[3])
circuit.delay(1495, qreg_q[4], unit='dt')
circuit.h(qreg_q[4])
circuit.barrier()

# Capa de señuelo 25
circuit.delay(179, qreg_q[0], unit='dt')
circuit.x(qreg_q[0])
circuit.delay(2097, qreg_q[1], unit='dt')
circuit.x(qreg_q[1])
circuit.delay(1272, qreg_q[2], unit='dt')
circuit.y(qreg_q[2])
circuit.delay(1627, qreg_q[3], unit='dt')
circuit.z(qreg_q[3])
circuit.delay(2633, qreg_q[4], unit='dt')
circuit.z(qreg_q[4])
circuit.barrier()

# Capa de señuelo 26
circuit.delay(1556, qreg_q[0], unit='dt')
circuit.x(qreg_q[0])
circuit.delay(2907, qreg_q[1], unit='dt')
circuit.x(qreg_q[1])
circuit.delay(1789, qreg_q[2], unit='dt')
circuit.s(qreg_q[2])
circuit.delay(655, qreg_q[3], unit='dt')
circuit.h(qreg_q[3])
circuit.delay(2471, qreg_q[4], unit='dt')
circuit.h(qreg_q[4])
circuit.barrier()

# Capa de señuelo 27
circuit.delay(1524, qreg_q[0], unit='dt')
circuit.s(qreg_q[0])
circuit.delay(1653, qreg_q[1], unit='dt')
circuit.x(qreg_q[1])
circuit.delay(552, qreg_q[2], unit='dt')
circuit.s(qreg_q[2])
circuit.delay(1404, qreg_q[3], unit='dt')
circuit.z(qreg_q[3])
circuit.delay(385, qreg_q[4], unit='dt')
circuit.s(qreg_q[4])
circuit.barrier()

# Capa de señuelo 28
circuit.delay(1225, qreg_q[0], unit='dt')
circuit.h(qreg_q[0])
circuit.delay(654, qreg_q[1], unit='dt')
circuit.y(qreg_q[1])
circuit.delay(2070, qreg_q[2], unit='dt')
circuit.y(qreg_q[2])
circuit.delay(2721, qreg_q[3], unit='dt')
circuit.h(qreg_q[3])
circuit.delay(2637, qreg_q[4], unit='dt')
circuit.z(qreg_q[4])
circuit.barrier()

# Capa de señuelo 29
circuit.delay(1426, qreg_q[0], unit='dt')
circuit.y(qreg_q[0])
circuit.delay(1969, qreg_q[1], unit='dt')
circuit.x(qreg_q[1])
circuit.delay(551, qreg_q[2], unit='dt')
circuit.s(qreg_q[2])
circuit.delay(1269, qreg_q[3], unit='dt')
circuit.s(qreg_q[3])
circuit.delay(1868, qreg_q[4], unit='dt')
circuit.s(qreg_q[4])
circuit.barrier()

# Capa de señuelo 30
circuit.delay(2554, qreg_q[0], unit='dt')
circuit.h(qreg_q[0])
circuit.delay(677, qreg_q[1], unit='dt')
circuit.z(qreg_q[1])
circuit.delay(2855, qreg_q[2], unit='dt')
circuit.s(qreg_q[2])
circuit.delay(2948, qreg_q[3], unit='dt')
circuit.z(qreg_q[3])
circuit.delay(1562, qreg_q[4], unit='dt')
circuit.x(qreg_q[4])
circuit.barrier()

# Capa de señuelo 31
circuit.delay(188, qreg_q[0], unit='dt')
circuit.x(qreg_q[0])
circuit.delay(990, qreg_q[1], unit='dt')
circuit.z(qreg_q[1])
circuit.delay(847, qreg_q[2], unit='dt')
circuit.h(qreg_q[2])
circuit.delay(1740, qreg_q[3], unit='dt')
circuit.s(qreg_q[3])
circuit.delay(2454, qreg_q[4], unit='dt')
circuit.y(qreg_q[4])
circuit.barrier()

# Capa de señuelo 32
circuit.delay(200, qreg_q[0], unit='dt')
circuit.h(qreg_q[0])
circuit.delay(1808, qreg_q[1], unit='dt')
circuit.h(qreg_q[1])
circuit.delay(2833, qreg_q[2], unit='dt')
circuit.x(qreg_q[2])
circuit.delay(2914, qreg_q[3], unit='dt')
circuit.z(qreg_q[3])
circuit.delay(1353, qreg_q[4], unit='dt')
circuit.h(qreg_q[4])
circuit.barrier()

# Capa de señuelo 33
circuit.delay(570, qreg_q[0], unit='dt')
circuit.s(qreg_q[0])
circuit.delay(892, qreg_q[1], unit='dt')
circuit.h(qreg_q[1])
circuit.delay(2258, qreg_q[2], unit='dt')
circuit.h(qreg_q[2])
circuit.delay(1276, qreg_q[3], unit='dt')
circuit.s(qreg_q[3])
circuit.delay(604, qreg_q[4], unit='dt')
circuit.s(qreg_q[4])
circuit.barrier()

# Capa de señuelo 34
circuit.delay(1204, qreg_q[0], unit='dt')
circuit.y(qreg_q[0])
circuit.delay(1555, qreg_q[1], unit='dt')
circuit.z(qreg_q[1])
circuit.delay(1491, qreg_q[2], unit='dt')
circuit.x(qreg_q[2])
circuit.delay(1576, qreg_q[3], unit='dt')
circuit.x(qreg_q[3])
circuit.delay(2741, qreg_q[4], unit='dt')
circuit.y(qreg_q[4])
circuit.barrier()

# Capa de señuelo 35
circuit.delay(2159, qreg_q[0], unit='dt')
circuit.h(qreg_q[0])
circuit.delay(2647, qreg_q[1], unit='dt')
circuit.x(qreg_q[1])
circuit.delay(915, qreg_q[2], unit='dt')
circuit.h(qreg_q[2])
circuit.delay(633, qreg_q[3], unit='dt')
circuit.x(qreg_q[3])
circuit.delay(2167, qreg_q[4], unit='dt')
circuit.s(qreg_q[4])
circuit.barrier()

# Capa de señuelo 36
circuit.delay(1970, qreg_q[0], unit='dt')
circuit.h(qreg_q[0])
circuit.delay(2196, qreg_q[1], unit='dt')
circuit.y(qreg_q[1])
circuit.delay(712, qreg_q[2], unit='dt')
circuit.x(qreg_q[2])
circuit.delay(1177, qreg_q[3], unit='dt')
circuit.s(qreg_q[3])
circuit.delay(431, qreg_q[4], unit='dt')
circuit.z(qreg_q[4])
circuit.barrier()

# Capa de señuelo 37
circuit.delay(2525, qreg_q[0], unit='dt')
circuit.h(qreg_q[0])
circuit.delay(1730, qreg_q[1], unit='dt')
circuit.z(qreg_q[1])
circuit.delay(1271, qreg_q[2], unit='dt')
circuit.z(qreg_q[2])
circuit.delay(513, qreg_q[3], unit='dt')
circuit.y(qreg_q[3])
circuit.delay(821, qreg_q[4], unit='dt')
circuit.s(qreg_q[4])
circuit.barrier()

# Capa de señuelo 38
circuit.delay(1638, qreg_q[0], unit='dt')
circuit.h(qreg_q[0])
circuit.delay(160, qreg_q[1], unit='dt')
circuit.h(qreg_q[1])
circuit.delay(1674, qreg_q[2], unit='dt')
circuit.s(qreg_q[2])
circuit.delay(2125, qreg_q[3], unit='dt')
circuit.y(qreg_q[3])
circuit.delay(2366, qreg_q[4], unit='dt')
circuit.h(qreg_q[4])
circuit.barrier()

# Capa de señuelo 39
circuit.delay(751, qreg_q[0], unit='dt')
circuit.s(qreg_q[0])
circuit.delay(1211, qreg_q[1], unit='dt')
circuit.x(qreg_q[1])
circuit.delay(279, qreg_q[2], unit='dt')
circuit.x(qreg_q[2])
circuit.delay(1174, qreg_q[3], unit='dt')
circuit.s(qreg_q[3])
circuit.delay(2585, qreg_q[4], unit='dt')
circuit.z(qreg_q[4])
circuit.barrier()

# Capa de señuelo 40
circuit.delay(349, qreg_q[0], unit='dt')
circuit.s(qreg_q[0])
circuit.delay(830, qreg_q[1], unit='dt')
circuit.s(qreg_q[1])
circuit.delay(214, qreg_q[2], unit='dt')
circuit.s(qreg_q[2])
circuit.delay(2208, qreg_q[3], unit='dt')
circuit.h(qreg_q[3])
circuit.delay(1991, qreg_q[4], unit='dt')
circuit.y(qreg_q[4])
circuit.barrier()

# Capa de señuelo 41
circuit.delay(1932, qreg_q[0], unit='dt')
circuit.s(qreg_q[0])
circuit.delay(279, qreg_q[1], unit='dt')
circuit.z(qreg_q[1])
circuit.delay(1338, qreg_q[2], unit='dt')
circuit.h(qreg_q[2])
circuit.delay(733, qreg_q[3], unit='dt')
circuit.h(qreg_q[3])
circuit.delay(694, qreg_q[4], unit='dt')
circuit.x(qreg_q[4])
circuit.barrier()

# Capa de señuelo 42
circuit.delay(963, qreg_q[0], unit='dt')
circuit.y(qreg_q[0])
circuit.delay(879, qreg_q[1], unit='dt')
circuit.z(qreg_q[1])
circuit.delay(1986, qreg_q[2], unit='dt')
circuit.y(qreg_q[2])
circuit.delay(2104, qreg_q[3], unit='dt')
circuit.h(qreg_q[3])
circuit.delay(1106, qreg_q[4], unit='dt')
circuit.z(qreg_q[4])
circuit.barrier()

# Capa de señuelo 43
circuit.delay(1199, qreg_q[0], unit='dt')
circuit.y(qreg_q[0])
circuit.delay(1129, qreg_q[1], unit='dt')
circuit.z(qreg_q[1])
circuit.delay(2243, qreg_q[2], unit='dt')
circuit.s(qreg_q[2])
circuit.delay(1291, qreg_q[3], unit='dt')
circuit.x(qreg_q[3])
circuit.delay(1462, qreg_q[4], unit='dt')
circuit.y(qreg_q[4])
circuit.barrier()

# Capa de señuelo 44
circuit.delay(1508, qreg_q[0], unit='dt')
circuit.h(qreg_q[0])
circuit.delay(1271, qreg_q[1], unit='dt')
circuit.x(qreg_q[1])
circuit.delay(1230, qreg_q[2], unit='dt')
circuit.h(qreg_q[2])
circuit.delay(1144, qreg_q[3], unit='dt')
circuit.z(qreg_q[3])
circuit.delay(1411, qreg_q[4], unit='dt')
circuit.x(qreg_q[4])
circuit.barrier()

# Capa de señuelo 45
circuit.delay(365, qreg_q[0], unit='dt')
circuit.z(qreg_q[0])
circuit.delay(1227, qreg_q[1], unit='dt')
circuit.z(qreg_q[1])
circuit.delay(1069, qreg_q[2], unit='dt')
circuit.y(qreg_q[2])
circuit.delay(1698, qreg_q[3], unit='dt')
circuit.h(qreg_q[3])
circuit.delay(2879, qreg_q[4], unit='dt')
circuit.x(qreg_q[4])
circuit.barrier()

# Capa de señuelo 46
circuit.delay(447, qreg_q[0], unit='dt')
circuit.h(qreg_q[0])
circuit.delay(2424, qreg_q[1], unit='dt')
circuit.z(qreg_q[1])
circuit.delay(2960, qreg_q[2], unit='dt')
circuit.h(qreg_q[2])
circuit.delay(1621, qreg_q[3], unit='dt')
circuit.s(qreg_q[3])
circuit.delay(1797, qreg_q[4], unit='dt')
circuit.s(qreg_q[4])
circuit.barrier()

# Capa de señuelo 47
circuit.delay(2023, qreg_q[0], unit='dt')
circuit.y(qreg_q[0])
circuit.delay(2511, qreg_q[1], unit='dt')
circuit.h(qreg_q[1])
circuit.delay(351, qreg_q[2], unit='dt')
circuit.y(qreg_q[2])
circuit.delay(2159, qreg_q[3], unit='dt')
circuit.x(qreg_q[3])
circuit.delay(1265, qreg_q[4], unit='dt')
circuit.y(qreg_q[4])
circuit.barrier()

# Capa de señuelo 48
circuit.delay(1247, qreg_q[0], unit='dt')
circuit.x(qreg_q[0])
circuit.delay(648, qreg_q[1], unit='dt')
circuit.y(qreg_q[1])
circuit.delay(1625, qreg_q[2], unit='dt')
circuit.y(qreg_q[2])
circuit.delay(2099, qreg_q[3], unit='dt')
circuit.z(qreg_q[3])
circuit.delay(1550, qreg_q[4], unit='dt')
circuit.x(qreg_q[4])
circuit.barrier()

# Capa de señuelo 49
circuit.delay(2660, qreg_q[0], unit='dt')
circuit.h(qreg_q[0])
circuit.delay(1888, qreg_q[1], unit='dt')
circuit.s(qreg_q[1])
circuit.delay(1713, qreg_q[2], unit='dt')
circuit.x(qreg_q[2])
circuit.delay(1011, qreg_q[3], unit='dt')
circuit.h(qreg_q[3])
circuit.delay(1607, qreg_q[4], unit='dt')
circuit.h(qreg_q[4])
circuit.barrier()

# Capa de señuelo 50
circuit.delay(1971, qreg_q[0], unit='dt')
circuit.z(qreg_q[0])
circuit.delay(416, qreg_q[1], unit='dt')
circuit.h(qreg_q[1])
circuit.delay(1977, qreg_q[2], unit='dt')
circuit.z(qreg_q[2])
circuit.delay(1754, qreg_q[3], unit='dt')
circuit.x(qreg_q[3])
circuit.delay(467, qreg_q[4], unit='dt')
circuit.y(qreg_q[4])
circuit.barrier()

# Mediciones finales
circuit.measure(qreg_q[0], creg_c[0])
circuit.measure(qreg_q[1], creg_c[1])
circuit.measure(qreg_q[2], creg_c[2])
circuit.measure(qreg_q[3], creg_c[3])
circuit.measure(qreg_q[4], creg_c[4])