from qiskit import QuantumRegister, ClassicalRegister, QuantumCircuit

qreg_q = QuantumRegister(5, 'q')
creg_c = ClassicalRegister(5, 'c')
circuit = QuantumCircuit(qreg_q, creg_c)

# --- INICIO DEL MURO DE SE�UELOS ---

# Capa de se�uelo 1
circuit.delay(2537, qreg_q[0], unit='dt')
circuit.s(qreg_q[0])
circuit.delay(1454, qreg_q[1], unit='dt')
circuit.x(qreg_q[1])
circuit.delay(1524, qreg_q[2], unit='dt')
circuit.z(qreg_q[2])
circuit.delay(1486, qreg_q[3], unit='dt')
circuit.z(qreg_q[3])
circuit.delay(941, qreg_q[4], unit='dt')
circuit.h(qreg_q[4])
circuit.barrier()

# Capa de se�uelo 2
circuit.delay(1419, qreg_q[0], unit='dt')
circuit.x(qreg_q[0])
circuit.delay(319, qreg_q[1], unit='dt')
circuit.y(qreg_q[1])
circuit.delay(1816, qreg_q[2], unit='dt')
circuit.z(qreg_q[2])
circuit.delay(1410, qreg_q[3], unit='dt')
circuit.z(qreg_q[3])
circuit.delay(2185, qreg_q[4], unit='dt')
circuit.h(qreg_q[4])
circuit.barrier()

# Capa de se�uelo 3
circuit.delay(2009, qreg_q[0], unit='dt')
circuit.x(qreg_q[0])
circuit.delay(2854, qreg_q[1], unit='dt')
circuit.y(qreg_q[1])
circuit.delay(980, qreg_q[2], unit='dt')
circuit.x(qreg_q[2])
circuit.delay(1930, qreg_q[3], unit='dt')
circuit.h(qreg_q[3])
circuit.delay(1340, qreg_q[4], unit='dt')
circuit.x(qreg_q[4])
circuit.barrier()

# Capa de se�uelo 4
circuit.delay(875, qreg_q[0], unit='dt')
circuit.x(qreg_q[0])
circuit.delay(2710, qreg_q[1], unit='dt')
circuit.s(qreg_q[1])
circuit.delay(1662, qreg_q[2], unit='dt')
circuit.x(qreg_q[2])
circuit.delay(2562, qreg_q[3], unit='dt')
circuit.s(qreg_q[3])
circuit.delay(2481, qreg_q[4], unit='dt')
circuit.x(qreg_q[4])
circuit.barrier()

# Capa de se�uelo 5
circuit.delay(1399, qreg_q[0], unit='dt')
circuit.y(qreg_q[0])
circuit.delay(2543, qreg_q[1], unit='dt')
circuit.x(qreg_q[1])
circuit.delay(2883, qreg_q[2], unit='dt')
circuit.z(qreg_q[2])
circuit.delay(2696, qreg_q[3], unit='dt')
circuit.z(qreg_q[3])
circuit.delay(459, qreg_q[4], unit='dt')
circuit.z(qreg_q[4])
circuit.barrier()

# Capa de se�uelo 6
circuit.delay(1221, qreg_q[0], unit='dt')
circuit.y(qreg_q[0])
circuit.delay(324, qreg_q[1], unit='dt')
circuit.z(qreg_q[1])
circuit.delay(998, qreg_q[2], unit='dt')
circuit.z(qreg_q[2])
circuit.delay(1743, qreg_q[3], unit='dt')
circuit.h(qreg_q[3])
circuit.delay(2078, qreg_q[4], unit='dt')
circuit.z(qreg_q[4])
circuit.barrier()

# Capa de se�uelo 7
circuit.delay(1893, qreg_q[0], unit='dt')
circuit.y(qreg_q[0])
circuit.delay(1261, qreg_q[1], unit='dt')
circuit.y(qreg_q[1])
circuit.delay(1262, qreg_q[2], unit='dt')
circuit.y(qreg_q[2])
circuit.delay(1409, qreg_q[3], unit='dt')
circuit.s(qreg_q[3])
circuit.delay(2945, qreg_q[4], unit='dt')
circuit.z(qreg_q[4])
circuit.barrier()

# Capa de se�uelo 8
circuit.delay(561, qreg_q[0], unit='dt')
circuit.s(qreg_q[0])
circuit.delay(2797, qreg_q[1], unit='dt')
circuit.z(qreg_q[1])
circuit.delay(1647, qreg_q[2], unit='dt')
circuit.z(qreg_q[2])
circuit.delay(457, qreg_q[3], unit='dt')
circuit.z(qreg_q[3])
circuit.delay(1108, qreg_q[4], unit='dt')
circuit.h(qreg_q[4])
circuit.barrier()

# Capa de se�uelo 9
circuit.delay(138, qreg_q[0], unit='dt')
circuit.y(qreg_q[0])
circuit.delay(1612, qreg_q[1], unit='dt')
circuit.z(qreg_q[1])
circuit.delay(372, qreg_q[2], unit='dt')
circuit.z(qreg_q[2])
circuit.delay(615, qreg_q[3], unit='dt')
circuit.h(qreg_q[3])
circuit.delay(2725, qreg_q[4], unit='dt')
circuit.s(qreg_q[4])
circuit.barrier()

# Capa de se�uelo 10
circuit.delay(1546, qreg_q[0], unit='dt')
circuit.x(qreg_q[0])
circuit.delay(2438, qreg_q[1], unit='dt')
circuit.z(qreg_q[1])
circuit.delay(1872, qreg_q[2], unit='dt')
circuit.s(qreg_q[2])
circuit.delay(670, qreg_q[3], unit='dt')
circuit.y(qreg_q[3])
circuit.delay(1468, qreg_q[4], unit='dt')
circuit.h(qreg_q[4])
circuit.barrier()

# Capa de se�uelo 11
circuit.delay(1539, qreg_q[0], unit='dt')
circuit.h(qreg_q[0])
circuit.delay(134, qreg_q[1], unit='dt')
circuit.s(qreg_q[1])
circuit.delay(2168, qreg_q[2], unit='dt')
circuit.h(qreg_q[2])
circuit.delay(576, qreg_q[3], unit='dt')
circuit.x(qreg_q[3])
circuit.delay(1005, qreg_q[4], unit='dt')
circuit.z(qreg_q[4])
circuit.barrier()

# Capa de se�uelo 12
circuit.delay(1013, qreg_q[0], unit='dt')
circuit.x(qreg_q[0])
circuit.delay(1472, qreg_q[1], unit='dt')
circuit.z(qreg_q[1])
circuit.delay(684, qreg_q[2], unit='dt')
circuit.x(qreg_q[2])
circuit.delay(918, qreg_q[3], unit='dt')
circuit.x(qreg_q[3])
circuit.delay(775, qreg_q[4], unit='dt')
circuit.x(qreg_q[4])
circuit.barrier()

# Capa de se�uelo 13
circuit.delay(1542, qreg_q[0], unit='dt')
circuit.s(qreg_q[0])
circuit.delay(455, qreg_q[1], unit='dt')
circuit.y(qreg_q[1])
circuit.delay(1922, qreg_q[2], unit='dt')
circuit.x(qreg_q[2])
circuit.delay(1548, qreg_q[3], unit='dt')
circuit.x(qreg_q[3])
circuit.delay(2950, qreg_q[4], unit='dt')
circuit.h(qreg_q[4])
circuit.barrier()

# Capa de se�uelo 14
circuit.delay(279, qreg_q[0], unit='dt')
circuit.h(qreg_q[0])
circuit.delay(2248, qreg_q[1], unit='dt')
circuit.h(qreg_q[1])
circuit.delay(2041, qreg_q[2], unit='dt')
circuit.x(qreg_q[2])
circuit.delay(1230, qreg_q[3], unit='dt')
circuit.s(qreg_q[3])
circuit.delay(2448, qreg_q[4], unit='dt')
circuit.y(qreg_q[4])
circuit.barrier()

# Capa de se�uelo 15
circuit.delay(2407, qreg_q[0], unit='dt')
circuit.h(qreg_q[0])
circuit.delay(1172, qreg_q[1], unit='dt')
circuit.y(qreg_q[1])
circuit.delay(2018, qreg_q[2], unit='dt')
circuit.z(qreg_q[2])
circuit.delay(2582, qreg_q[3], unit='dt')
circuit.x(qreg_q[3])
circuit.delay(2284, qreg_q[4], unit='dt')
circuit.y(qreg_q[4])
circuit.barrier()

# Capa de se�uelo 16
circuit.delay(241, qreg_q[0], unit='dt')
circuit.x(qreg_q[0])
circuit.delay(2596, qreg_q[1], unit='dt')
circuit.s(qreg_q[1])
circuit.delay(2232, qreg_q[2], unit='dt')
circuit.z(qreg_q[2])
circuit.delay(1094, qreg_q[3], unit='dt')
circuit.s(qreg_q[3])
circuit.delay(331, qreg_q[4], unit='dt')
circuit.s(qreg_q[4])
circuit.barrier()

# Capa de se�uelo 17
circuit.delay(2695, qreg_q[0], unit='dt')
circuit.z(qreg_q[0])
circuit.delay(2108, qreg_q[1], unit='dt')
circuit.z(qreg_q[1])
circuit.delay(2355, qreg_q[2], unit='dt')
circuit.s(qreg_q[2])
circuit.delay(2193, qreg_q[3], unit='dt')
circuit.x(qreg_q[3])
circuit.delay(1134, qreg_q[4], unit='dt')
circuit.z(qreg_q[4])
circuit.barrier()

# Capa de se�uelo 18
circuit.delay(876, qreg_q[0], unit='dt')
circuit.x(qreg_q[0])
circuit.delay(2346, qreg_q[1], unit='dt')
circuit.s(qreg_q[1])
circuit.delay(188, qreg_q[2], unit='dt')
circuit.y(qreg_q[2])
circuit.delay(348, qreg_q[3], unit='dt')
circuit.s(qreg_q[3])
circuit.delay(2097, qreg_q[4], unit='dt')
circuit.x(qreg_q[4])
circuit.barrier()

# Capa de se�uelo 19
circuit.delay(794, qreg_q[0], unit='dt')
circuit.s(qreg_q[0])
circuit.delay(1449, qreg_q[1], unit='dt')
circuit.s(qreg_q[1])
circuit.delay(2151, qreg_q[2], unit='dt')
circuit.z(qreg_q[2])
circuit.delay(1729, qreg_q[3], unit='dt')
circuit.z(qreg_q[3])
circuit.delay(1888, qreg_q[4], unit='dt')
circuit.x(qreg_q[4])
circuit.barrier()

# Capa de se�uelo 20
circuit.delay(1412, qreg_q[0], unit='dt')
circuit.x(qreg_q[0])
circuit.delay(1811, qreg_q[1], unit='dt')
circuit.y(qreg_q[1])
circuit.delay(2499, qreg_q[2], unit='dt')
circuit.h(qreg_q[2])
circuit.delay(2290, qreg_q[3], unit='dt')
circuit.s(qreg_q[3])
circuit.delay(936, qreg_q[4], unit='dt')
circuit.s(qreg_q[4])
circuit.barrier()

# Capa de se�uelo 21
circuit.delay(1604, qreg_q[0], unit='dt')
circuit.x(qreg_q[0])
circuit.delay(1934, qreg_q[1], unit='dt')
circuit.h(qreg_q[1])
circuit.delay(2297, qreg_q[2], unit='dt')
circuit.h(qreg_q[2])
circuit.delay(1688, qreg_q[3], unit='dt')
circuit.y(qreg_q[3])
circuit.delay(1327, qreg_q[4], unit='dt')
circuit.x(qreg_q[4])
circuit.barrier()

# Capa de se�uelo 22
circuit.delay(1752, qreg_q[0], unit='dt')
circuit.x(qreg_q[0])
circuit.delay(134, qreg_q[1], unit='dt')
circuit.h(qreg_q[1])
circuit.delay(2842, qreg_q[2], unit='dt')
circuit.x(qreg_q[2])
circuit.delay(960, qreg_q[3], unit='dt')
circuit.z(qreg_q[3])
circuit.delay(466, qreg_q[4], unit='dt')
circuit.h(qreg_q[4])
circuit.barrier()

# Capa de se�uelo 23
circuit.delay(1566, qreg_q[0], unit='dt')
circuit.h(qreg_q[0])
circuit.delay(145, qreg_q[1], unit='dt')
circuit.h(qreg_q[1])
circuit.delay(1842, qreg_q[2], unit='dt')
circuit.x(qreg_q[2])
circuit.delay(2852, qreg_q[3], unit='dt')
circuit.z(qreg_q[3])
circuit.delay(204, qreg_q[4], unit='dt')
circuit.z(qreg_q[4])
circuit.barrier()

# Capa de se�uelo 24
circuit.delay(2390, qreg_q[0], unit='dt')
circuit.s(qreg_q[0])
circuit.delay(1385, qreg_q[1], unit='dt')
circuit.z(qreg_q[1])
circuit.delay(2396, qreg_q[2], unit='dt')
circuit.s(qreg_q[2])
circuit.delay(513, qreg_q[3], unit='dt')
circuit.z(qreg_q[3])
circuit.delay(1149, qreg_q[4], unit='dt')
circuit.x(qreg_q[4])
circuit.barrier()

# Capa de se�uelo 25
circuit.delay(1568, qreg_q[0], unit='dt')
circuit.x(qreg_q[0])
circuit.delay(194, qreg_q[1], unit='dt')
circuit.z(qreg_q[1])
circuit.delay(2840, qreg_q[2], unit='dt')
circuit.z(qreg_q[2])
circuit.delay(1099, qreg_q[3], unit='dt')
circuit.x(qreg_q[3])
circuit.delay(2639, qreg_q[4], unit='dt')
circuit.z(qreg_q[4])
circuit.barrier()

# Mediciones finales
circuit.measure(qreg_q[0], creg_c[0])
circuit.measure(qreg_q[1], creg_c[1])
circuit.measure(qreg_q[2], creg_c[2])
circuit.measure(qreg_q[3], creg_c[3])
circuit.measure(qreg_q[4], creg_c[4])